create table
  public.buyers (
    id serial,
    name character varying(255) not null,
    address character varying(255) not null,
    country character varying(50) not null,
    vatnumber character varying(50) null,
    contractnumber character varying(50) null,
    contactperson character varying(255) null,
    paymentterm character varying(50) null,
    deliveryterm character varying(50) null,
    registrationnumber character varying(50) null,
    currency_id integer null default 1,
    contactpersonrole text null default ''::text,
    constraint buyers_pkey primary key (id),
    constraint buyers_currency_id_fkey foreign key (currency_id) references currencies (id)
  ) tablespace pg_default;

create table
  public.currencies (
    id serial,
    name character varying(50) not null,
    symbol character varying(10) not null,
    constraint currencies_pkey primary key (id)
  ) tablespace pg_default;

create table
  public.invoice_design (
    id integer generated by default as identity,
    created_at timestamp with time zone not null default now(),
    logo text null,
    slogan text null default ''::text,
    footer text null default ''::text,
    color text null,
    constraint invoice_design_id_fkey foreign key (id) references sellers (id)
  ) tablespace pg_default;


create table
  public.invoice_products (
    id serial,
    invoicenumber character varying(50) null,
    product_id integer null,
    units integer not null,
    unitprice numeric(10, 2) not null,
    unitvat numeric(5, 2) not null,
    unittotal numeric(10, 2) not null,
    productlot text null default ''::text,
    languageversion text null default ''::text,
    constraint invoice_products_pkey primary key (id),
    constraint invoice_products_invoicenumber_fkey foreign key (invoicenumber) references invoices (invoicenumber),
    constraint invoice_products_product_id_fkey foreign key (product_id) references products (id)
  ) tablespace pg_default;


create table
  public.invoices (
    invoicenumber character varying(50) not null,
    vattype character varying(50) null,
    date date not null,
    deliveryterm character varying(50) null,
    deliverydate date null,
    paymentsplit character varying(255) null,
    subtotal numeric(10, 2) null,
    total numeric(10, 2) null,
    taxrate numeric(5, 2) null,
    totaltax numeric(10, 2) null,
    totaldiscount numeric(10, 2) null,
    discountrate numeric(5, 2) null,
    numberinwords text null,
    comments text null,
    paymentstatus character varying(50) null,
    buyer_id integer null,
    seller_id integer null,
    currency_id integer null default 1,
    time_stamp timestamp with time zone null default (now() at time zone 'utc'::text),
    constraint invoices_pkey primary key (invoicenumber),
    constraint invoices_buyer_id_fkey foreign key (buyer_id) references buyers (id),
    constraint invoices_currency_id_fkey foreign key (currency_id) references currencies (id),
    constraint invoices_seller_id_fkey foreign key (seller_id) references sellers (id)
  ) tablespace pg_default;

create table
  public.products (
    id serial,
    name character varying(255) not null,
    description text null,
    category character varying(255) null,
    price numeric(10, 2) not null,
    time_stamp timestamp with time zone null default (now() at time zone 'utc'::text),
    defaultquantity numeric null default '0'::numeric,
    maxquantity numeric null default '0'::numeric,
    imageurl text null,
    status text null default 'active'::text,
    constraint products_pkey primary key (id),
    constraint products_status_check check (
      (
        (status = 'active'::text)
        or (status = 'archived'::text)
        or (status = 'deleted'::text)
      )
    )
  ) tablespace pg_default;

  create table
  public.sellers (
    id serial,
    name character varying(255) not null,
    address character varying(255) not null,
    vatnumber character varying(50) null,
    displayname character varying(255) null,
    managingdirector character varying(255) null,
    country character varying(50) null,
    constraint sellers_pkey primary key (id)
  ) tablespace pg_default;

  create table
  public.bank_details (
    id serial,
    iban character varying(50) not null,
    bank character varying(255) not null,
    bic character varying(50) not null,
    seller_id integer null,
    constraint bank_details_pkey primary key (id),
    constraint bank_details_seller_id_fkey foreign key (seller_id) references sellers (id)
  ) tablespace pg_default;

  